### ISSUE TITLE
Some way to request cards in other languages?

### ISSUE THREAD

**Issue by LucasAlfare** [Wildric-Auric/YuGiOh-Database#1]
I was wondering the implementation of this in order to make possible get the cards in another language, such as Portuguese. What do you think about?

**Comment by Wildric-Auric** [comment]
Sure it's possible, the current version is bad. It should be reimplemented using apis instead of pure scrapping.
However it seems the fandom does not offer api [anymore](https://www.reddit.com/r/learnpython/comments/n8al5o/fandom_wiki_api/). Maybe different website apis will be combined.
For Portuguese especially, with the same method already used, I can get cards description, name, attributes... but for images I don't know if it's possible to get them in Portuguese.
